apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
  namespace: dev
  labels:
    app.kubernetes.io/name: test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test1
    spec:
      imagePullSecrets:
        - name: test1-acr-secret
      containers:
        - name: harshalitetenantdev
          image: rg23aks-eehybhbhdxh8cyb9.azurecr.io/test1:nginx-v1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 1Gi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test1
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test1
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: v1
kind: Service
metadata:
  name: test1
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: test1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
